version: '3'
services:
  weatherapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "345124qe"
      DB_DATABASE: "weather"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "345124qe"
      POSTGRES_DB:  "weather"
